export const testIds = {
  authEmail: "auth-email",
  authPassword: "auth-password",
  authSubmit: "auth-submit",
  authSwitch: "auth-switch",
  tabToday: "tab-today",
  tabPlan: "tab-plan",
  tabFocus: "tab-focus",
  tabReview: "tab-review",
  addSchedule: "add-schedule",
  scheduleTitle: "schedule-title",
  scheduleSubject: "schedule-subject",
  scheduleDate: "schedule-date",
  scheduleTopics: "schedule-topics",
  saveSchedule: "save-schedule",
  parseText: "parse-text",
  parseButton: "parse-button",
  taskInput: "task-input",
  addTask: "add-task",
  timerStart: "timer-start",
  recallFront: "recall-front",
  recallBack: "recall-back",
  createCard: "create-card",
} as const;